### ISSUE TITLE
Mobile site improvements

### ISSUE THREAD

**Issue by ikilledmypc** [Fdebijl/EmojiBuilder#2]
List of emoticon doesn't show on mobile

**Comment by Fdebijl** [comment]
Emoji enumeration is fixed, will add mobile stylesheet to better facilitate mobile users.

**Comment by Fdebijl** [comment]
Fixed mobile style with https://github.com/Fdebijl/EmojiBuilder/commit/dd93e79db083e6ce684d51a08813cb8253a65591, should also add functionality to drag SVG paths on mobile.
