### ISSUE TITLE
upon saving I get blank image

### ISSUE THREAD

**Issue by diomed** [Fdebijl/EmojiBuilder#9]
it's like I saved nothing but empty space.

**Comment by Fdebijl** [comment]
Thanks for putting in a bug report! This issue is being worked on at the moment ( #1 ), I expect to have it fixed somewhere next week.

**Comment by Fdebijl** [comment]
Should be fixed now, go ahead and give it a whirl. If you encounter any issues, feel free to reopen this one.

**Comment by diomed** [comment]
![emoji 1](https://user-images.githubusercontent.com/72777/31731363-153f48ae-b435-11e7-8195-3ab6dbdb8404.png)
Thanks!
